# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

name: Deploy Bicep files

variables:

  resourceGroupName: 'tfstate4243'
  location: 'westeurope'
  templateFile: './main.bicep'        # The entry point
  scriptType: 'batch'                 # use batch for Windows and 'bash' for Linux build agents

pool:
  name: 'Default'

stages:
- stage: Setup_Stg_Account
  displayName: Setup Stg Account for Terraform State

  jobs:
  - job: Create_Storage_Account
    displayName: 'Create Storage Account'

    steps:
    - task: AzureCLI@2
      inputs:
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        azureSubscription: 'SC4TF'
        scriptType: $(scriptType)
        scriptLocation: inlineScript
        inlineScript: |
          az --version
          az deployment sub create --location $(location) --template-file main.bicep
