# Pipeline
# Use to setup a resource group and a storage account to hold the terrafrom state

trigger:
- master

name: Deploy Bicep files

variables:

  location: 'westeurope'
  scriptType: 'batch'                 # use 'batch' for Windows and 'bash' for Linux build agents
  stgAccountRgName: 'tfstate47'
  stgAccountName: 'sastate474747'
  stgAccountContainerName: 'sastate47'

pool:
  name: 'Default'

stages:
- stage: Setup_Stg_Account
  displayName: Setup Stg Account for Terraform State

  jobs:
  - job: Create_Storage_Account
    displayName: 'Create Storage Account'

    steps:
    - task: AzureCLI@2
      inputs:
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        azureSubscription: 'SC4TF'
        scriptType: $(scriptType)
        scriptLocation: inlineScript
        inlineScript: |
          echo 'Setting up storage acoount $(stgAccountName) in RG $(stgAccountRgName) with container $(stgAccountContainerName)'
          az deployment sub create ^
          --location $(location) ^
          --template-file main.bicep --parameters stgAccountRgName=$(stgAccountRgName) ^ 
          --parameters 'stgAccountName=$(stgAccountName)' ^
          --parameters 'stgAccountContainerName=$(stgAccountContainerName)' 
