# Pipeline
# Use to setup a resource group and a storage account to hold the terrafrom state
# Use script type 'batch' with a Windows agent and 'bash' with a Linux agent
# Note: Use as New Line character for multi-line commands with batch ^ and with bash \

trigger:
- master

name: Deploy Bicep files

variables:

  location: 'westeurope'
  stgAccountRgName: 'rg-tfstate'
  stgAccountName: 'stgacctfstate4243'
  stgAccountContainerName: 'stgacc-tfstate-demo'

pool:
  name: 'Default'

stages:
- stage: Setup_Stg_Account
  displayName: Setup Stg Account for Terraform State

  jobs:
  - job: Create_Storage_Account
    displayName: 'Create Storage Account'

    steps:
    - task: AzureCLI@2
      inputs:
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        azureSubscription: 'SC4TF'
        scriptType: batch
        scriptLocation: inlineScript
        inlineScript: |
          echo 'Setting up storage acoount $(stgAccountName) in RG $(stgAccountRgName) with container $(stgAccountContainerName)'
          az deployment sub create ^
          --location $(location) ^
          --template-file main.bicep ^
          --parameters stgAccountRgName=$(stgAccountRgName) ^
          --parameters stgAccountName=$(stgAccountName) ^
          --parameters stgAccountContainerName=$(stgAccountContainerName)
